component: http
name: api
inputs:
  src:
    hook: pip3 install -r requirements.txt -t ./
    dist: ./
    exclude:
      - .env
      - requirements/**
      - __pycache__/**
  region: ap-guangzhou
  faas:
    framework: flask
    name: ${name}
    runtime: Python3.6
  apigw:
    protocols:
      - http
      - https
app: demo
